# Generated by Django 4.2.5 on 2023-10-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllStocks',
            new_name='Stock',
        ),
    ]
